name: build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_PR_NUM: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ! -z "${GH_PR_NUM}" ]]; then 
            echo "Checking out PR"
            git fetch origin pull/$GH_PR_NUM/head:tmp
            git checkout tmp
          fi
      - uses: actions/cache@v2
        id: setup-cache
        name: Cache setup
        with:
          path: |
            README.md
            package.json
            .tmplr.yml
            packages/*/package.json
            packages/*/patternfly-docs/content/**
            packages/*/patternfly-docs/generated/**
          key: ${{ runner.os }}-setup-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('package.json', 'packages/module/package.json') }}
      - name: Run build script
        run: ./devSetup.sh
        shell: bash
        if: steps.setup-cache.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Cache npm deps
        with:
          path: |
           node_modules
           **/node_modules
          key: ${{ runner.os }}-yarn-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: dist
        name: Cache dist
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-dist-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock', 'package.json', 'packages/*/*', '!packages/*/dist', '!packages/*/node_modules') }}
      - name: Build dist
        run: yarn build
        if: steps.dist.outputs.cache-hit != 'true'